// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("ebfe7617-ae3a-468a-abcc-c0e5a84529a5"),
	Geocodio("d14ae9c3-ac72-41a7-b3aa-acc0057ae58f"),
	LocationIQ("2c099df0-ad51-43cb-a9ec-35c8253d5d54"),
	MapQuest("9d1b6f19-1c57-49de-82ed-57830b8630f4");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
