// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("49f063a0-f1f6-43c3-b6ec-4e59c3b90065"),
	Geocodio("9347aae7-5962-4ae4-8183-d3c1fe52ebe7"),
	LocationIQ("448e4e7c-fdaf-415d-a394-1daa2eb2f90f"),
	MapQuest("5a1dde85-4e3a-45a4-aac6-e0cdb5c7ac8b");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
