// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("3e2eb409-9869-4722-a43d-a6e6b4d80e0c"),
	startsWith("18f20eeb-993f-4bc2-9263-ab6a83bfc674"),
	endsWith("03f35f0b-55a2-4544-a408-0de0081a6df7"),
	between("2cbbe288-59a3-47b6-960c-a5338ec16065"),
	greater("321c9829-68ea-4b54-8f52-32efdbb58745"),
	greaterEqual("b7e2ddd1-3a9d-4303-b405-f376a455d5c5"),
	equal("355ff48b-0243-4aab-b4bf-333854d78d65"),
	notEqual("b3c64a36-18d6-457c-b005-0c41398c1f1e"),
	smaller("261a5806-b3fb-445c-990f-d8d1cb43d4be"),
	smallerEqual("aff18b82-d6c4-4bc0-a7e4-ef05b7a94429"),
	empty("f460dbdf-6757-4d61-8e99-7ac2c1da80de"),
	notEmpty("242f405a-b577-4093-b42d-c72b351dabc0");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
