// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("406670ea-2462-4b44-8208-1572fd9791d9"),
	startsWith("41d868b3-9c4b-44a7-a8e1-41357787421f"),
	endsWith("14588b06-b1cc-43f0-9859-1647218a3995"),
	between("9e2f8ab0-0b88-4ea0-be42-ba9cedbe3f2a"),
	greater("556cf725-a41f-4dc9-aafa-e8d05af7ae37"),
	greaterEqual("2550322b-6044-4c64-a092-191be790d498"),
	equal("e6b888f0-3d3d-4d58-9d01-abf6290fdfdd"),
	notEqual("ee866132-f2cd-4581-8b35-7aaf5d1af43e"),
	smaller("03794f9a-de00-4ce6-a7fe-4efc968975e2"),
	smallerEqual("48829c2e-0518-43e5-afb2-53c2326f5729"),
	empty("7aa60c68-c8e5-4535-93e4-4cd4313e1205"),
	notEmpty("a2b2f100-17f0-40a6-8854-ffe15322930b");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
